name: CardForge CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install flake8

      - name: Lint
        run: |
          flake8 cardforge --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 cardforge --count --exit-zero --max-complexity=12 --max-line-length=127 --statistics

      - name: Run tests
        run: |
          pytest -v --maxfail=3 --disable-warnings

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: .pytest_cache
